[workspace]
resolver = "2"
members = [
    "crates/shared",
    "crates/broker",
    "crates/claude-attach",
    "crates/hook-stop",
    "crates/hook-notification",
    "crates/hook-pretool",
    "crates/hook-posttool",
    "crates/platform-discord",
    "crates/agentmux-cli",
    "crates/agentmux-tray",
]

[workspace.package]
version = "0.2.2"
edition = "2021"
rust-version = "1.75"

[profile.release]
opt-level = "z"
lto = true
codegen-units = 1
strip = true
panic = "abort"
